spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: application-datasource.yml, application-setting.yml, application-${spring.profiles.active}.yml

server:
  address: 0.0.0.0
  port: ${PORT:8080}
