spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}  # Railway에서는 prod 프로파일 사용
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: application-datasource.yml, application-setting.yml, application-${spring.profiles.active}.yml
  
  # 파일 업로드 크기 제한 설정
  servlet:
    multipart:
      max-file-size: 10MB        # 개별 파일 최대 크기
      max-request-size: 10MB     # 전체 요청 최대 크기
      enabled: true
  
  # 스케줄러 설정
  task:
    scheduling:
      enabled: true
      pool:
        size: 1

server:
  address: 0.0.0.0
  port: ${PORT:8080}