spring:
  datasource:
    url: ${ORACLE_DATASOURCE_URL}
    username: ${ORACLE_DATASOURCE_USERNAME}
    password: ${ORACLE_DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000