spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
        id:
          new_generator_mappings: false
  config:
    import: application-datasource.yml, application-setting.yml, application-${spring.profiles.active}.yml

server:
  address: 0.0.0.0
  port: ${PORT:8083}  # hanacard는 8083 포트 사용

# 하나그린세상 연동 설정
hana-green-world:
  api:
    base-url: ${HANA_GREEN_WORLD_API_URL:http://localhost:8080}
