server:
  address: 0.0.0.0
  port: ${PORT:8080} 

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

logging:
  level:
    com.kopo.hanacard: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
